### ISSUE TITLE
Create Major Recruiters Logo Slider

### ISSUE THREAD

**Issue by vascodes** [vascodes/rcss-placement-cell#4]
### TODO: 
- [x] Update "Popular Courses" section to show "Our Major Recruiters".
- [x] Remove cards and replace with logo slider.
- [x] Update logos in logo slider with major recruiters.

### Some Major Recruiters are shown in below image:

![Image](https://user-images.githubusercontent.com/70539432/219935386-c435a262-10d2-46c9-8182-02090542358c.png)

**Comment by Mohdalthaf** [comment]
completed
